# Generated by Django 4.1.6 on 2023-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
            ],
            options={
                "verbose_name": "本",
                "verbose_name_plural": "本",
                "db_table": "book",
            },
        ),
    ]
