# Generated by Django 4.1.6 on 2023-02-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="著者名")),
            ],
            options={"db_table": "author",},
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="出版社名")),
            ],
            options={"db_table": "publisher",},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="画像"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="価格"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="概要"),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日"),
                ),
                ("authors", models.ManyToManyField(to="app.author", verbose_name="著者")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app.publisher",
                        verbose_name="出版社",
                    ),
                ),
            ],
            options={"db_table": "book",},
        ),
    ]
